 const cardMap = {
  'The Magician': '1. The Magician.jpg',
  'The High Priestess': '2. The High Priestess.jpg',
  'The Empress': '3. The Empress.jpg',
  'The Emperor': '4. The Emperor.jpg',
  'The Hierophant': '5. The Hierophant.jpg',
  'The Lovers': '6. The Lovers.jpg',
  'The Chariot': '7. The Chariot.jpg',
  'Strength': '8. Strength.jpg',
  'The Hermit': '9. The Hermit.jpg',
  'Wheel Of Fortune': '10. Wheel Of Fortune.jpg',
  'Justice': '11. Justice.jpg',
  'The Hanged Man': '12. The Hanged Man.jpg',
  'Death': '13. Death.jpg',
  'Temperance': '14. Temperance.jpg',
  'The Devil': '15. The Devil.jpg',
  'The Tower': '16. The Tower.jpg',
  'The Star': '17. The Star.jpg',
  'The Moon': '18. The Moon.jpg',
  'The Sun': '19. The Sun.jpg',
  'Judgement': '20. Judgement.jpg',
  'The World': '21. The World.jpg',
  'Ace of Cups': 'Ace Of Cups.jpg',
  'Ace of Pentacles': 'Ace Of Pentacles.jpg',
  'Ace of Swords': 'Ace Of Swords.jpg',
  'Ace of Wands': 'Ace Of Wands.jpg',
  'Two of Cups': 'Two Of Cups.jpg',
  'Two of Pentacles': 'Two Of Pentacles.jpg',
  'Two of Swords': 'Two Of Swords.jpg',
  'Two of Wands': 'Two Of Wands.jpg',
  'Three of Cups': 'Three Of Cups.jpg',
  'Three of Pentacles': 'Three Of Pentacles.jpg',
  'Three of Swords': 'Three Of Swords.jpg',
  'Three of Wands': 'Three Of Wands.jpg',
  'Four of Cups': 'Four Of Cups.jpg',
  'Four of Pentacles': 'Four Of Pentacles.jpg',
  'Four of Swords': 'Four Of Swords.jpg',
  'Four of Wands': 'Four Of Wands.jpg',
  'Five of Cups': 'Five Of Cups.jpg',
  'Five of Pentacles': 'Five Of Pentacles.jpg',
  'Five of Swords': 'Five Of Swords.jpg',
  'Five of Wands': 'Five Of Wands.jpg',
  'Six of Cups': 'Six Of Cups.jpg',
  'Six of Pentacles': 'Six Of Pentacles.jpg',
  'Six of Swords': 'Six Of Swords.jpg',
  'Six of Wands': 'Six Of Wands.jpg',
  'Seven of Cups': 'Seven Of Cups.jpg',
  'Seven of Pentacles': 'Seven Of Pentacles.jpg',
  'Seven of Swords': 'Seven Of Swords.jpg',
  'Seven of Wands': 'Seven Of Wands.jpg',
  'Eight of Cups': 'Eight Of Cups.jpg',
  'Eight of Pentacles': 'Eight Of Pentacles.jpg',
  'Eight of Swords': 'Eight Of Swords.jpg',
  'Eight of Wands': 'Eight Of Wands.jpg',
  'Nine of Cups': 'Nine Of Cups.jpg',
  'Nine of Pentacles': 'Nine Of Pentacles.jpg',
  'Nine of Swords': 'Nine Of Swords.jpg',
  'Nine of Wands': 'Nine Of Wands.jpg',
  'Ten of Cups': 'Ten Of Cups.jpg',
  'King of Cups': 'King Of Cups.jpg',
  'King of Pentacles': 'King Of Pentacles.jpg',
  'King of Swords': 'King Of Swords.jpg',
  'King of Wands': 'King Of Wands.jpg',
  'Knight of Cups': 'Knight Of Cups.jpg',
  'Knight of Pentacles': 'Knight Of Pentacles.jpg',
  'Knight of Swords': 'Knight Of Swords.jpg',
  'Knight of Wands': 'Knight Of Wands.jpg',
  'Page of Cups': 'Page Of Cups.jpg',
  'Page of Pentacles': 'Page Of Pentacles.jpg',
  'Page of Swords': 'Page Of Swords.jpg',
  'Page of Wands': 'Page Of Wands.jpg',
  'Queen of Cups': 'Queen Of Cups.jpg',
  'Queen of Pentacles': 'Queen Of Pentacles.jpg',
  'Queen of Swords': 'Queen Of Swords.jpg',
  'Queen of Wands': 'Queen Of Wands.jpg',
  'Ten of Pentacles': 'Ten Of Pentacles.jpg',
  'Ten of Swords': 'Ten Of Swords.jpg',
  'Ten of Wands': 'Ten Of Wands.jpg',
  'The Fool': 'The Fool.jpg'
}



export default cardMap